<?xml version="1.0"?>

<robot name="quadruped_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<material name="Red">
		<color rgba="1.0 0.0 0.0 1.0"/>
	</material>

	<material name="Green">
		<color rgba="0.0 1.0 0.0 1.0"/>
	</material>

	<material name="Blue">
		<color rgba="0.0 0.0 1.0 1.0"/>
	</material>

	<material name="Brown">
		<color rgba="0.5 0.5 0.0 1.0"/>
	</material>

	<xacro:property name="link_mu" value="0.6"/>
	<xacro:property name="link_kp" value="1e6"/>
	<xacro:property name="link_kd" value="1"/>
	<xacro:property name="link_max_vel" value="0.01"/>
	<xacro:property name="link_min_depth" value="0.001"/>
	<xacro:property name="soft_cfm" value="0.01"/>
	<xacro:property name="soft_erp" value="0.3"/>
	
	<xacro:property name="body_length" value="0.183"/>
	<xacro:property name="body_width" value="0.16"/>
	<xacro:property name="body_height" value="0.05"/>
	<xacro:property name="L1_length" value="0.046"/>
	<xacro:property name="L2_length" value="0.066"/>
	<xacro:property name="L3_length" value="0.065"/>
	<xacro:property name="leg_radius" value="0.01"/>

	<xacro:property name="body_mass" value="1.42"/>
	<xacro:property name="L1_mass" value="0.04"/>
	<xacro:property name="L2_mass" value="0.04"/>
	<xacro:property name="L3_mass" value="0.04"/>
	<xacro:property name="foot_mass" value="0.04"/>

	<xacro:property name="joint_damping" value="0.0"/>
	<xacro:property name="joint_friction" value="0.01"/>

	<xacro:property name="max_joint_torque" value="100.0"/>
	<xacro:property name="max_joint_velocity" value="300.0"/>


	<xacro:property name="actual_body_length" value="0.183"/>
	<xacro:property name="actual_body_width" value="0.16"/>
	<xacro:property name="robot_init_height" value="0.25"/>


	<xacro:property name="joint_controller_interface" value="$(arg joint_controller_interface)"/>

<!--////////////////////////    inertial macro    //////////////////////////-->
	<xacro:macro name="cylinder_inertial_matrix" params="origin_xyz origin_rpy mass length radius">
		<inertial>
			<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
			<mass value="${mass}"/>
			<inertia ixx="${mass*(3*radius*radius+length*length)/12.0}" ixy="0.0" ixz="0.0" iyy="${mass*(3*radius*radius+length*length)/12.0}" iyz="0.0" izz="${mass*radius*radius/2.0}" />
		</inertial>
	</xacro:macro>

	<xacro:macro name="sphere_inertial_matrix" params="origin_xyz origin_rpy mass radius">
		<inertial>
			<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
			<mass value="${mass}"/>
			<inertia ixx="${mass*radius*radius*2.0/5.0}" ixy="0.0" ixz="0.0" iyy="${mass*radius*radius*2.0/5.0}" iyz="0.0" izz="${mass*radius*radius*2.0/5.0}" />
		</inertial>
	</xacro:macro>

<!--////////////////////////    surface macro    //////////////////////////-->
	<xacro:macro name="link_surface" params="mu kp kd max_vel min_depth">
		<surface>
            <bounce>
              <restitution_coefficient>0.5</restitution_coefficient> 
              <threshold>0.001</threshold>
            </bounce>
            <friction>
              <torsional>
                <coefficient>${mu}</coefficient>
                <surface_radius>0.05</surface_radius>
                <ode>
                  <slip>0</slip>
                </ode>
              </torsional>
              <ode>
                <mu>${mu}</mu>
                <mu2>${mu}</mu2>
                <fdir1>0 0 0</fdir1>
                <slip1>0</slip1>
                <slip2>0</slip2>
              </ode>
            </friction>
            <contact>
              <ode>
			  	<soft_cfm>${soft_cfm}</soft_cfm>
			  	<soft_erp>${soft_erp}</soft_erp>
                <kp value="${kp}" />
                <kd value="${kd}" />
                <max_vel>${max_vel}</max_vel>
                <min_depth>${min_depth}</min_depth>
              </ode>
            </contact>
          </surface>
	</xacro:macro>

<!--////////////////////////    joint macro    //////////////////////////-->
	<xacro:macro name="leg_joint" params="joint_name joint_type parent_link child_link origin_xyz origin_rpy axis_xyz lower upper">
		  <joint name="${joint_name}" type="${joint_type}">
   			 <parent link="${parent_link}"/>
   			 <child link="${child_link}"/>
   			 <origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
   			 <axis xyz="${axis_xyz}" />
   			 <limit effort="${max_joint_torque}" velocity="${max_joint_velocity}" lower="${lower}" upper="${upper}"/>
   		 	 <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
	 	 </joint>
	</xacro:macro>

<!--////////////////////////    link macro    //////////////////////////-->
    <xacro:macro name="leg_link" params="link_name origin_xyz origin_rpy mass length radius">
  		<link name="${link_name}" >
    			<visual>
      				<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      				<geometry>
            				<cylinder radius="${radius}" length="${length}"/>
      				</geometry>
      				<material name="Brown" />
    			</visual>

    			<collision>
      				<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      				<geometry>
            				<cylinder radius="${radius}" length="${length}"/>
      				</geometry>
					<xacro:link_surface  mu="${link_mu}" kp="${link_kp}" kd="${link_kd}" max_vel="${link_max_vel}" min_depth="${link_min_depth}"  />
    			</collision>
    			<xacro:cylinder_inertial_matrix  origin_xyz="${origin_xyz}" origin_rpy="${origin_rpy}" mass="${mass}" radius="${radius}" length="${length}"/>
  		</link>
	</xacro:macro>

<!--////////////////////////    foot link macro    //////////////////////////-->
    <xacro:macro name="foot_link" params="link_name origin_xyz origin_rpy mass radius">
  		<link name="${link_name}" >
    			<visual>
      				<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      				<geometry>
            				<sphere radius="${radius}"/>
      				</geometry>
      				<material name="Red" />
    			</visual>

    			<collision>
      				<origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      				<geometry>
            				<sphere radius="${radius}"/>
      				</geometry>
    			</collision>
    			<xacro:sphere_inertial_matrix origin_xyz="${origin_xyz}" origin_rpy="${origin_rpy}" mass="${mass}" radius="${radius}" />
  		</link>
 	</xacro:macro>


<!--////////////////////////    leg macro    //////////////////////////-->
    <xacro:macro name="leg" params="leg_name origin_xyz">
        <xacro:leg_joint  joint_name="${leg_name}1_joint" joint_type="revolute" parent_link="body_link" child_link="${leg_name}1_link" origin_xyz="${origin_xyz}" origin_rpy="0 0 0" axis_xyz="1 0 0" lower="-1.57" upper="1.57"/>
		<xacro:leg_link link_name="${leg_name}1_link" origin_xyz="0 0 ${-L1_length/2}" origin_rpy="0 0 0" mass="${L1_mass}" length="${L1_length}" radius="${leg_radius}"/>
        <xacro:leg_joint  joint_name="${leg_name}2_joint" joint_type="revolute" parent_link="${leg_name}1_link" child_link="${leg_name}2_link" origin_xyz="0 0 ${-L1_length}" origin_rpy="0 0 0" axis_xyz="0 1 0" lower="${-3.14*1.0}" upper="${3.14*1.0}"/>
		<xacro:leg_link link_name="${leg_name}2_link" origin_xyz="0 0 ${-L2_length/2}" origin_rpy="0 0 0" mass="${L2_mass}" length="${L2_length}" radius="${leg_radius}"/>
        <xacro:leg_joint  joint_name="${leg_name}3_joint" joint_type="revolute" parent_link="${leg_name}2_link" child_link="${leg_name}3_link" origin_xyz="0 0 ${-L2_length}" origin_rpy="0 0 0" axis_xyz="0 1 0" lower="${-3.14*1.0}" upper="${3.14*1.0}"/>
		<xacro:leg_link link_name="${leg_name}3_link" origin_xyz="0 0 ${-L3_length/2}" origin_rpy="0 0 0" mass="${L3_mass}" length="${L3_length}" radius="${leg_radius}"/>
        <xacro:leg_joint  joint_name="${leg_name}4_joint" joint_type="fixed" parent_link="${leg_name}3_link" child_link="${leg_name}Foot_link" origin_xyz="0 0 ${-L3_length}" origin_rpy="0 0 0" axis_xyz="0 1 0" lower="-0.00001" upper="0.0"/>
		<!--<xacro:leg_link link_name="${leg_name}4_link" origin_xyz="0 0 ${-L3_length/2}" origin_rpy="0 0 0" length="${L3_length}" />-->
		<xacro:foot_link  link_name="${leg_name}Foot_link" origin_xyz="0 0 0" origin_rpy="0 0 0" mass="${foot_mass}" radius="${leg_radius*1.2}" />
	</xacro:macro>

<!--////////////////////////    transmission macro    //////////////////////////-->
	<!-- <xacro:macro name="transmission_block" params="joint_name">
		<transmission name="tran1">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${joint_name}">
				<hardwareInterface>${joint_controller_interface}</hardwareInterface>
			</joint>
			<actuator name="motor1">
				<hardwareInterface>${joint_controller_interface}</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro> -->


<!--/////////////////////////   word link  /////////////////////////////////// -->
<!--/////////////////////////   Body define  /////////////////////////////////// -->
	<link name="body_link">

 		<visual>
			<origin xyz="0 0 ${robot_init_height*0}" rpy="0 0 0"/>
			<geometry>
				<box size="${actual_body_length} ${actual_body_width} ${body_height}"/>
			</geometry>
			<material name="Green"/>
		</visual>

		<collision>
			<origin xyz="0 0 ${robot_init_height*0}" rpy="0 0 0"/>
			<geometry>
				<box size="${actual_body_length} ${actual_body_width} ${body_height}"/>
			</geometry>
		</collision>

		<inertial>
     		<origin xyz="0 0 ${robot_init_height*0}" rpy="0 0 0"/>
     		<mass value="${body_mass}"/>
     		<inertia ixx="${body_mass*(body_width*body_width+body_height*body_height)/12.0}"  ixy="0"  ixz="0" iyy="${body_mass*(body_length*body_length+body_height*body_height)/12.0}" iyz="0" izz="${body_mass*(body_length*body_length+body_width*body_width)/12.0}" />
   		</inertial>

	</link>

<!--////////////////////////    Leg define   //////////////////////////-->
	<xacro:leg leg_name="LF" origin_xyz="${body_length/2.0} ${body_width/2.0} ${robot_init_height*0}" /> 
	<xacro:leg leg_name="RF" origin_xyz="${body_length/2.0} ${-body_width/2.0} ${robot_init_height*0}" /> 
	<xacro:leg leg_name="LH" origin_xyz="${-body_length/2.0} ${body_width/2.0} ${robot_init_height*0}" /> 
	<xacro:leg leg_name="RH" origin_xyz="${-body_length/2.0} ${-body_width/2.0} ${robot_init_height*0}" /> 

<!--////////////////////////    tansmission define   //////////////////////////-->
<!-- 
	<xacro:transmission_block joint_name="LF1_joint"/>
   	<xacro:transmission_block joint_name="LF2_joint"/>
   	<xacro:transmission_block joint_name="LF3_joint"/>
	<xacro:transmission_block joint_name="RF1_joint"/>
	<xacro:transmission_block joint_name="RF2_joint"/>
	<xacro:transmission_block joint_name="RF3_joint"/>
	<xacro:transmission_block joint_name="LH1_joint"/>
	<xacro:transmission_block joint_name="LH2_joint"/>
	<xacro:transmission_block joint_name="LH3_joint"/>
	<xacro:transmission_block joint_name="RH1_joint"/>
	<xacro:transmission_block joint_name="RH2_joint"/>
	<xacro:transmission_block joint_name="RH3_joint"/> -->

</robot>
